name: Generate Language Pie Chart

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Language Graph
        uses: denvercoder1/github-readme-stats@master
        with:
          username: JP-rocha23
          hide: css,html,jupyter notebook,markdown
          theme: nord
          layout: donut
          output: generated/languages.svg

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update languages chart" || exit 0
          git push
